docs(helmet): update helmet import
Using the previous import command `import * as helmet from 'helmet'` results in the following error:

```
src/main.ts:40:11 - error TS2349: This expression is not callable.
  Type 'typeof import("/home/node_modules/helmet/dist/types/index")' has no call signatures.

40   app.use(helmet());
             ~~~~~~
```

Since helmet provides it's own types and the default export is callable, it should be done as the changes in the page indicate.